/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "gray-1": "#FCFCFD",
        "gray-2": "#F9F9FB",
        "gray-3": "#EFF0F3",
        "gray-4": "#E7E8EC",
        "gray-5": "#E0E1E6",
        "gray-6": "#D8D9E0",
        "gray-7": "#CDCED7",
        "gray-8": "#B9BBC6",
        "gray-9": "#8B8D98",
        "gray-10": "#80828D",
        "gray-11": "#62636C",
        "gray-12": "#1E1F24",
        "blue-1": "#fdfdfe",
        "blue-2": "#f7f9ff",
        "blue-3": "#edf2fe",
        "blue-4": "#dfeaff",
        "blue-5": "#d0dfff",
        "blue-6": "#bdd1ff",
        "blue-7": "#a6bff9",
        "blue-8": "#87a5ef",
        "blue-9": "#3d63dd",
        "blue-10": "#3657c3",
        "blue-11": "#395bc7",
        "blue-12": "#1d2e5c",
        "blue-contrast": "#fff",
        "blue-surface": "#f5f8ffcc",
        "blue-indicator": "#3d63dd",
        "blue-track": "#3d63dd",
      },
    },
  },
  plugins: [],
};
