export const clients = [
  {
    name: "Ana Beatriz Souza",
    account_number: "102345-1",
    email: "ana.souza@example.com",
    status: "active",
    balance: 15320.45,
    account_type: "corrente",
    created_at: "2021-03-15",
  },
  {
    name: "Lucas Pereira",
    account_number: "102346-2",
    email: "lucas.pereira@example.com",
    status: "active",
    balance: 2850.0,
    account_type: "poupança",
    created_at: "2022-06-10",
  },
  {
    name: "Mariana Costa",
    account_number: "102347-3",
    email: "mariana.costa@example.com",
    status: "suspended",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2020-11-22",
  },
  {
    name: "João Henrique Silva",
    account_number: "102348-4",
    email: "joao.henrique@example.com",
    status: "active",
    balance: 980.65,
    account_type: "poupança",
    created_at: "2023-02-03",
  },
  {
    name: "Patrícia Almeida",
    account_number: "102349-5",
    email: "patricia.almeida@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2019-08-17",
  },
  {
    name: "Carlos Eduardo Lima",
    account_number: "102350-6",
    email: "carlos.lima@example.com",
    status: "active",
    balance: 45000.32,
    account_type: "empresarial",
    created_at: "2020-12-01",
  },
  {
    name: "Fernanda Ribeiro",
    account_number: "102351-7",
    email: "fernanda.ribeiro@example.com",
    status: "active",
    balance: 755.8,
    account_type: "poupança",
    created_at: "2022-01-27",
  },
  {
    name: "Rodrigo Martins",
    account_number: "102352-8",
    email: "rodrigo.martins@example.com",
    status: "active",
    balance: 1500.1,
    account_type: "corrente",
    created_at: "2023-07-19",
  },
  {
    name: "Juliana Rocha",
    account_number: "102353-9",
    email: "juliana.rocha@example.com",
    status: "suspended",
    balance: 50.0,
    account_type: "corrente",
    created_at: "2021-09-25",
  },
  {
    name: "Gabriel Nunes",
    account_number: "102354-0",
    email: "gabriel.nunes@example.com",
    status: "active",
    balance: 10200.0,
    account_type: "empresarial",
    created_at: "2020-04-11",
  },
  {
    name: "Laura Mendes",
    account_number: "102355-1",
    email: "laura.mendes@example.com",
    status: "active",
    balance: 870.9,
    account_type: "corrente",
    created_at: "2023-05-14",
  },
  {
    name: "Felipe Santos",
    account_number: "102356-2",
    email: "felipe.santos@example.com",
    status: "active",
    balance: 3045.7,
    account_type: "poupança",
    created_at: "2022-12-09",
  },
  {
    name: "Isabela Duarte",
    account_number: "102357-3",
    email: "isabela.duarte@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2018-02-20",
  },
  {
    name: "Thiago Carvalho",
    account_number: "102358-4",
    email: "thiago.carvalho@example.com",
    status: "active",
    balance: 19200.4,
    account_type: "empresarial",
    created_at: "2021-10-02",
  },
  {
    name: "Camila Ferreira",
    account_number: "102359-5",
    email: "camila.ferreira@example.com",
    status: "active",
    balance: 500.0,
    account_type: "poupança",
    created_at: "2023-03-28",
  },
  {
    name: "Ricardo Barbosa",
    account_number: "102360-6",
    email: "ricardo.barbosa@example.com",
    status: "active",
    balance: 720.25,
    account_type: "corrente",
    created_at: "2020-06-15",
  },
  {
    name: "Sofia Oliveira",
    account_number: "102361-7",
    email: "sofia.oliveira@example.com",
    status: "active",
    balance: 16750.1,
    account_type: "empresarial",
    created_at: "2019-11-30",
  },
  {
    name: "Bruno Castro",
    account_number: "102362-8",
    email: "bruno.castro@example.com",
    status: "active",
    balance: 300.0,
    account_type: "corrente",
    created_at: "2022-04-12",
  },
  {
    name: "Tatiane Gomes",
    account_number: "102363-9",
    email: "tatiane.gomes@example.com",
    status: "suspended",
    balance: 15.5,
    account_type: "poupança",
    created_at: "2021-01-09",
  },
  {
    name: "Pedro Azevedo",
    account_number: "102364-0",
    email: "pedro.azevedo@example.com",
    status: "active",
    balance: 1205.9,
    account_type: "corrente",
    created_at: "2023-08-22",
  },
];
