export const clients = [
  {
    name: "Ana Beatriz Souza",
    account_number: "102345-1",
    email: "ana.souza@example.com",
    status: "active",
    balance: 15320.45,
    account_type: "corrente",
    created_at: "2021-03-15",
  },
  {
    name: "Lucas Pereira",
    account_number: "102346-2",
    email: "lucas.pereira@example.com",
    status: "active",
    balance: 2850.0,
    account_type: "poupança",
    created_at: "2022-06-10",
  },
  {
    name: "Mariana Costa",
    account_number: "102347-3",
    email: "mariana.costa@example.com",
    status: "suspended",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2020-11-22",
  },
  {
    name: "João Henrique Silva",
    account_number: "102348-4",
    email: "joao.henrique@example.com",
    status: "active",
    balance: 980.65,
    account_type: "poupança",
    created_at: "2023-02-03",
  },
  {
    name: "Patrícia Almeida",
    account_number: "102349-5",
    email: "patricia.almeida@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2019-08-17",
  },
  {
    name: "Carlos Eduardo Lima",
    account_number: "102350-6",
    email: "carlos.lima@example.com",
    status: "active",
    balance: 45000.32,
    account_type: "empresarial",
    created_at: "2020-12-01",
  },
  {
    name: "Fernanda Ribeiro",
    account_number: "102351-7",
    email: "fernanda.ribeiro@example.com",
    status: "active",
    balance: 755.8,
    account_type: "poupança",
    created_at: "2022-01-27",
  },
  {
    name: "Rodrigo Martins",
    account_number: "102352-8",
    email: "rodrigo.martins@example.com",
    status: "active",
    balance: 1500.1,
    account_type: "corrente",
    created_at: "2023-07-19",
  },
  {
    name: "Juliana Rocha",
    account_number: "102353-9",
    email: "juliana.rocha@example.com",
    status: "suspended",
    balance: 50.0,
    account_type: "corrente",
    created_at: "2021-09-25",
  },
  {
    name: "Gabriel Nunes",
    account_number: "102354-0",
    email: "gabriel.nunes@example.com",
    status: "active",
    balance: 10200.0,
    account_type: "empresarial",
    created_at: "2020-04-11",
  },
  {
    name: "Laura Mendes",
    account_number: "102355-1",
    email: "laura.mendes@example.com",
    status: "active",
    balance: 870.9,
    account_type: "corrente",
    created_at: "2023-05-14",
  },
  {
    name: "Felipe Santos",
    account_number: "102356-2",
    email: "felipe.santos@example.com",
    status: "active",
    balance: 3045.7,
    account_type: "poupança",
    created_at: "2022-12-09",
  },
  {
    name: "Isabela Duarte",
    account_number: "102357-3",
    email: "isabela.duarte@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2018-02-20",
  },
  {
    name: "Thiago Carvalho",
    account_number: "102358-4",
    email: "thiago.carvalho@example.com",
    status: "active",
    balance: 19200.4,
    account_type: "empresarial",
    created_at: "2021-10-02",
  },
  {
    name: "Camila Ferreira",
    account_number: "102359-5",
    email: "camila.ferreira@example.com",
    status: "active",
    balance: 500.0,
    account_type: "poupança",
    created_at: "2023-03-28",
  },
  {
    name: "Ricardo Barbosa",
    account_number: "102360-6",
    email: "ricardo.barbosa@example.com",
    status: "active",
    balance: 720.25,
    account_type: "corrente",
    created_at: "2020-06-15",
  },
  {
    name: "Sofia Oliveira",
    account_number: "102361-7",
    email: "sofia.oliveira@example.com",
    status: "active",
    balance: 16750.1,
    account_type: "empresarial",
    created_at: "2019-11-30",
  },
  {
    name: "Bruno Castro",
    account_number: "102362-8",
    email: "bruno.castro@example.com",
    status: "active",
    balance: 300.0,
    account_type: "corrente",
    created_at: "2022-04-12",
  },
  {
    name: "Tatiane Gomes",
    account_number: "102363-9",
    email: "tatiane.gomes@example.com",
    status: "suspended",
    balance: 15.5,
    account_type: "poupança",
    created_at: "2021-01-09",
  },
  {
    name: "Pedro Azevedo",
    account_number: "102364-0",
    email: "pedro.azevedo@example.com",
    status: "active",
    balance: 1205.9,
    account_type: "corrente",
    created_at: "2023-08-22",
  },
  {
    name: "Daniela Pires",
    account_number: "102365-1",
    email: "daniela.pires@example.com",
    status: "active",
    balance: 3200.0,
    account_type: "poupança",
    created_at: "2021-05-11",
  },
  {
    name: "Rafael Monteiro",
    account_number: "102366-2",
    email: "rafael.monteiro@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2019-09-02",
  },
  {
    name: "Paula Lima",
    account_number: "102367-3",
    email: "paula.lima@example.com",
    status: "active",
    balance: 14560.3,
    account_type: "empresarial",
    created_at: "2020-12-20",
  },
  {
    name: "Leonardo Silva",
    account_number: "102368-4",
    email: "leonardo.silva@example.com",
    status: "suspended",
    balance: 400.0,
    account_type: "corrente",
    created_at: "2022-08-14",
  },
  {
    name: "Amanda Torres",
    account_number: "102369-5",
    email: "amanda.torres@example.com",
    status: "active",
    balance: 950.5,
    account_type: "poupança",
    created_at: "2023-04-19",
  },
  {
    name: "Eduardo Costa",
    account_number: "102370-6",
    email: "eduardo.costa@example.com",
    status: "active",
    balance: 18900.75,
    account_type: "empresarial",
    created_at: "2021-07-03",
  },
  {
    name: "Vanessa Martins",
    account_number: "102371-7",
    email: "vanessa.martins@example.com",
    status: "active",
    balance: 680.3,
    account_type: "corrente",
    created_at: "2022-02-15",
  },
  {
    name: "Gustavo Nogueira",
    account_number: "102372-8",
    email: "gustavo.nogueira@example.com",
    status: "active",
    balance: 12500.0,
    account_type: "empresarial",
    created_at: "2020-11-18",
  },
  {
    name: "Beatriz Faria",
    account_number: "102373-9",
    email: "beatriz.faria@example.com",
    status: "active",
    balance: 275.9,
    account_type: "poupança",
    created_at: "2023-01-10",
  },
  {
    name: "Alexandre Mendes",
    account_number: "102374-0",
    email: "alexandre.mendes@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2018-10-07",
  },
  {
    name: "Letícia Barbosa",
    account_number: "102375-1",
    email: "leticia.barbosa@example.com",
    status: "active",
    balance: 10450.0,
    account_type: "empresarial",
    created_at: "2020-05-29",
  },
  {
    name: "Marcelo Vieira",
    account_number: "102376-2",
    email: "marcelo.vieira@example.com",
    status: "active",
    balance: 3500.45,
    account_type: "corrente",
    created_at: "2022-06-09",
  },
  {
    name: "Cláudia Nascimento",
    account_number: "102377-3",
    email: "claudia.nascimento@example.com",
    status: "suspended",
    balance: 75.2,
    account_type: "poupança",
    created_at: "2021-11-03",
  },
  {
    name: "Renato Almeida",
    account_number: "102378-4",
    email: "renato.almeida@example.com",
    status: "active",
    balance: 20900.9,
    account_type: "empresarial",
    created_at: "2019-12-17",
  },
  {
    name: "Larissa Souza",
    account_number: "102379-5",
    email: "larissa.souza@example.com",
    status: "active",
    balance: 630.0,
    account_type: "corrente",
    created_at: "2023-09-26",
  },
  {
    name: "Diego Oliveira",
    account_number: "102380-6",
    email: "diego.oliveira@example.com",
    status: "active",
    balance: 920.7,
    account_type: "poupança",
    created_at: "2022-07-30",
  },
  {
    name: "Helena Carvalho",
    account_number: "102381-7",
    email: "helena.carvalho@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2018-03-11",
  },
  {
    name: "Caio Mendes",
    account_number: "102382-8",
    email: "caio.mendes@example.com",
    status: "active",
    balance: 11780.5,
    account_type: "empresarial",
    created_at: "2020-09-23",
  },
  {
    name: "Bruna Silva",
    account_number: "102383-9",
    email: "bruna.silva@example.com",
    status: "active",
    balance: 520.8,
    account_type: "poupança",
    created_at: "2023-02-08",
  },
  {
    name: "Matheus Rocha",
    account_number: "102384-0",
    email: "matheus.rocha@example.com",
    status: "active",
    balance: 2100.0,
    account_type: "corrente",
    created_at: "2021-06-01",
  },
  {
    name: "Viviane Gomes",
    account_number: "102385-1",
    email: "viviane.gomes@example.com",
    status: "active",
    balance: 14250.75,
    account_type: "empresarial",
    created_at: "2019-10-28",
  },
  {
    name: "Ricardo Tavares",
    account_number: "102386-2",
    email: "ricardo.tavares@example.com",
    status: "suspended",
    balance: 90.0,
    account_type: "corrente",
    created_at: "2022-05-13",
  },
  {
    name: "Tatiana Moreira",
    account_number: "102387-3",
    email: "tatiana.moreira@example.com",
    status: "active",
    balance: 640.2,
    account_type: "poupança",
    created_at: "2023-03-02",
  },
  {
    name: "Hugo Pereira",
    account_number: "102388-4",
    email: "hugo.pereira@example.com",
    status: "active",
    balance: 23500.0,
    account_type: "empresarial",
    created_at: "2020-01-22",
  },
  {
    name: "Priscila Fernandes",
    account_number: "102389-5",
    email: "priscila.fernandes@example.com",
    status: "active",
    balance: 780.6,
    account_type: "corrente",
    created_at: "2023-07-08",
  },
  {
    name: "André Lima",
    account_number: "102390-6",
    email: "andre.lima@example.com",
    status: "active",
    balance: 8700.0,
    account_type: "empresarial",
    created_at: "2021-09-18",
  },
  {
    name: "Gabriela Araujo",
    account_number: "102391-7",
    email: "gabriela.araujo@example.com",
    status: "active",
    balance: 1300.3,
    account_type: "poupança",
    created_at: "2022-11-07",
  },
  {
    name: "Fernando Duarte",
    account_number: "102392-8",
    email: "fernando.duarte@example.com",
    status: "closed",
    balance: 0.0,
    account_type: "corrente",
    created_at: "2018-04-19",
  },
  {
    name: "Monique Campos",
    account_number: "102393-9",
    email: "monique.campos@example.com",
    status: "active",
    balance: 19750.55,
    account_type: "empresarial",
    created_at: "2020-02-14",
  },
  {
    name: "Vitor Henrique",
    account_number: "102394-0",
    email: "vitor.henrique@example.com",
    status: "active",
    balance: 550.9,
    account_type: "corrente",
    created_at: "2023-08-03",
  },
];
